name: Deploy GitHub Contribution Grid Snake

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  push-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push GitHub Contribution Grid Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN
